environment:
  EXECUTABLE: python.exe
  VENV: NO
  PIP_DIR: Scripts
  matrix:
    # For the versions of python available and we are using
    
    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python27-x64"
    - PYTHON: "C:\\Python34"
    - PYTHON: "C:\\Python35-x64"
    - PYTHON: "C:\\Python36-x64"
    - PYTHON: "C:\\Python37"
    - PYTHON: "C:\\Python37-x64"
#    - PYTHON: c:/vp/pypy2
#      EXECUTABLE: bin/pypy.exe
#      PIP_DIR: bin
#      VENV: YES

install:
  # We need wheel installed to build wheels
  - ps: |
        if ($env:PYTHON -eq "c:/vp/pypy2")
        {
            c:\Projects\RfcEditor\winbuild\appveyor_install_pypy.cmd
        }
  - "%PYTHON%\\%EXECUTABLE% -m pip install wheel"
  - "%PYTHON%\\%EXECUTABLE% -m pip install -r requirements.txt"

build: off

test_script:
  - dir
  - set PATH=%PYTHON%\Scripts;%PATH%;%cd%\win32\aspell\bin;%cd%\win32\hunspell;%cd%\rfclint\win32
  - set DICTIONARY=en_US
  - set DICPATH=%cd%\win32\hunspell
  - cd rfctools_common
  - "%PYTHON%\\%EXECUTABLE% setup.py --quiet install"
  - cd rfctools_common
  - "%PYTHON%\\%EXECUTABLE% test.py"
  - cd ..\..
  - cd svgcheck
  - "%PYTHON%\\%EXECUTABLE% setup.py --quiet install"
  - cd svgcheck
  - "%PYTHON%\\%EXECUTABLE% test.py"
  - cd ..\..
  - cd rfclint
  - "%PYTHON%\\%EXECUTABLE% setup.py --quiet install"
  - cd rfclint
  - "%PYTHON%\\%EXECUTABLE% test.py"
  - cd ..\..
  - cd xmldiff
  - "%PYTHON%\\%EXECUTABLE% setup.py --quiet install"
  - cd Test
  - "%PYTHON%\\%EXECUTABLE% test.py"
  
after_test:
  - cd ..
  - "%PYTHON%\\%EXECUTABLE% setup.py bdist_wheel"

artifacts:
  - path: xmldiff\dist\*

#matrix:
#  fast_finish: true
